version: "2.1"

services:
  oracle:
    image: daggerok/oracle:11.2.0.2-xe
    shm_size: 1g
    environment:
      ORACLE_PWD: oraclepassword
    ports: ["1521:1521"]
    networks: [backing-services]
    healthcheck:
      test: curl -uSYSTEM:$$ORACLE_PWD -v http://127.0.0.1:8080//apex/
      interval: 10s
      timeout: 2s
      retries: 22

networks:
  backing-services:
    driver: bridge
