version: "2.1"
services:
  rabbitmq:
    image: healthcheck/rabbitmq:alpine
    volumes: ["rabbitmq-data:/var/lib/rabbitmq"]
    ports: ["5672:5672"]
    networks: [backing-services]
volumes:
  rabbitmq-data: {}
networks:
  backing-services:
    driver: bridge
