 my-rabbitmq:
   image: rabbitmq
   container_name: my-rabbitmq
   ports:
     - "5672:5672"

# # rabbit admin: http://localhost:15672
# my-rabbit-admin:
#   image: rabbitmq:3-management
#   container_name: my-rabbitmq-admin
#   environment:
#     RABBITMQ_DEFAULT_USER: test
#     RABBITMQ_DEFAULT_PASS: test
#   ports:
#     - "5672:5672"
#     - "15672:15672"
#     - "25672:25672"
