version: "2.1"

services:

  rabbitmq:
    restart: unless-stopped
    build: ../rabbitmq/custom
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
      - "rabbitmq-data:/etc/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [backing-services]

  app:
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    build: .
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    volumes: ["app-data:/home/app"]
    ports: ["8888:8888"]
    networks: [backing-services]

volumes:
  rabbitmq-data: {}
  app-data: {}

networks:
  backing-services:
    driver: bridge
