jenkins:
  container_name: jenkins
  image: 'jenkins:2.32.1'
  ports:
    - '50000:50000'
    - '8080:8080'
  volumes:
    - './var/jenkins_home:/var/jenkins_home'

# jenkins-from-dokerfile-container:
#   container_name: jenkins-from-dokerfile-container
#   build: .
#   image: 'jenkins:2.32.1'
#   ports:
#     - '50000:50000'
#     - '8080:8080'
#   volumes:
#     - './var/jenkins_home:/var/jenkins_home'
