version: '2.1'
services:
  postgres:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: ['5432:5432']
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      timeout: 3s
      retries: 33
      interval: 30s
    restart: unless-stopped
    networks:
      backing-services:
        aliases:
        - p
        - pg
        - db
        - postgres
    #mem_limit: 786432000 # container limit: 700Mb (700 * 1024 * 1024)
networks:
  backing-services:
    driver: bridge
