my-mongo:
  container_name: my-mongo # a custom mongo container_name
  image: mongo
  environment:
    - MONGO_PORT_27017_TCP_ADDR=localhost
    - MONGO_PORT_27017_TCP_PORT=27017
  ports:
    - "27017:27017"

##https://github.com/mongo-express/mongo-express-docker
#my-mongo-express:
#  container_name: my-mongo-express
#  image: mongo-express
#  ports:
#    - "8081:8081"
#  links:
#    - mongo # a custom mongo container_name
#  environment:
#    # should be a custom mongo container name:
#    ME_CONFIG_MONGODB_SERVER: my-mongo
#    ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
#    ME_CONFIG_SITE_BASEURL: /
